#ifndef INCLUDED_tracer_fp_h_
#define INCLUDED_tracer_fp_h_

#include "fp_shared_core.h"
#include "tracer_fp_batch_types.h"
#include "tracer_fp_types.h"

#ifdef __cplusplus
extern "C" {
#endif

int tracer_fp_cpu_threads(void);
void tracer_fp_cpu_ws_free(TracerFpCpuWs *ws);

int tracer_fp_cpu_evolve(int ncell,
                         int nstep,
                         double dt,
                         int use_windowed_reacc,
                         int on_start_step,
                         int on_end_step,
                         const CRspectrum *crp_grid,
                         const CRspectrum *cre_grid,
                         const double *n_gas,
                         const double *kbt,
                         const double *b_field,
                         const double *divv_gyr,
                         const double *l_turb_mpc,
                         const double *dv_imc,
                         const double *cs,
                         const double *beta_pl,
                         const double *rad_ic_batch,
                         const double *rad_ic_m1,
                         const double *rad_ic_p1,
                         const double *qpi_batch,
                         const double *qepri_batch,
                         const double *fqe_flat,
                         const int *np_min_qe,
                         const double *tracer_mass,
                         const unsigned char *disable_adiabatic,
                         double *crp_state,
                         double *cre_state,
                         TracerFpGpuTimes *times,
                         TracerFpCpuWs *ws);

int tracer_fp_batch_pack_bucket(int bucket_count,
                                const int *bucket_indices,
                                int coeff_interp_segments,
                                int ntracer_stride,
                                const double *n_gas_snap,
                                const double *kbt_snap,
                                const double *b_field_snap,
                                const double *divv_snap,
                                const double *lturb_snap,
                                const double *dv_snap,
                                const double *cs_snap,
                                const double *beta_snap,
                                const double *rad_ic_zero,
                                const double *rad_ic_m1_zero,
                                const double *rad_ic_p1_zero,
                                const double *n_gas_next_snap,
                                const double *kbt_next_snap,
                                const double *b_field_next_snap,
                                const double *divv_next_snap,
                                const double *lturb_next_snap,
                                const double *dv_next_snap,
                                const double *cs_next_snap,
                                const double *beta_next_snap,
                                const double *rad_ic_row_next,
                                double rad_ic_m1_next_val,
                                double rad_ic_p1_next_val,
                                const double *qpi_batch,
                                const double *qepri_batch,
                                const double *tracer_mass,
                                const unsigned char *disable_adiabatic,
                                const double *crp_state,
                                const double *cre_state,
                                const double *b_dyn,
                                const double *logb,
                                TracerFpCpuWs *cpu_ws,
                                TracerFpGpuHostWs *gpu_ws,
                                TracerFpGpuTimes *times);

void tracer_fp_batch_scatter_bucket_state(int bucket_count,
                                          const int *bucket_indices,
                                          double *crp_state,
                                          double *cre_state,
                                          const TracerFpCpuWs *cpu_ws,
                                          TracerFpGpuTimes *times);

int tracer_fp_batch_pack_group_current(int group_bucket_count,
                                       const int *group_bucket_ids,
                                       const TracerBucket *bucket,
                                       int ntracer_stride,
                                       const double *n_gas_snap,
                                       const double *kbt_snap,
                                       const double *b_field_snap,
                                       const double *divv_snap,
                                       const double *lturb_snap,
                                       const double *dv_snap,
                                       const double *cs_snap,
                                       const double *beta_snap,
                                       const double *rad_ic_zero,
                                       const double *rad_ic_m1_zero,
                                       const double *rad_ic_p1_zero,
                                       const double *n_gas_next_snap,
                                       const double *kbt_next_snap,
                                       const double *b_field_next_snap,
                                       const double *divv_next_snap,
                                       const double *lturb_next_snap,
                                       const double *dv_next_snap,
                                       const double *cs_next_snap,
                                       const double *beta_next_snap,
                                       const double *rad_ic_row_next,
                                       double rad_ic_m1_next_val,
                                       double rad_ic_p1_next_val,
                                       const double *qpi_batch,
                                       const double *qepri_batch,
                                       const double *tracer_mass,
                                       const unsigned char *disable_adiabatic,
                                       const double *crp_state,
                                       const double *cre_state,
                                       const double *b_dyn,
                                       const double *logb,
                                       int *cell_offsets_out,
                                       int *rad_ic_offsets_out,
                                       TracerFpCpuWs *cpu_ws,
                                       TracerFpGpuHostWs *gpu_ws,
                                       TracerFpGpuTimes *times);

void tracer_fp_batch_scatter_group_state(int group_bucket_count,
                                         const int *group_bucket_ids,
                                         const TracerBucket *bucket,
                                         const int *cell_offsets,
                                         double *crp_state,
                                         double *cre_state,
                                         const TracerFpCpuWs *cpu_ws,
                                         TracerFpGpuTimes *times);

int tracer_fp_batch_execute_bucket(int bucket_count,
                                   const int *bucket_indices,
                                   int bucket_nstep,
                                   int bucket_n_on,
                                   int bucket_base_nstep,
                                   int bucket_fp_cadence,
                                   TracerFpIntegrationMode integration_mode,
                                   int coeff_interp_segments,
                                   int allow_snapshot_interp,
                                   int ntracer_stride,
                                   double elapsed_gyr,
                                   double dt_snap,
                                   double z_curr,
                                   double z_next,
                                   double requested_t_acc_direct_gyr,
                                   const CRspectrum *crp_grid,
                                   const CRspectrum *cre_grid,
                                   const double *n_gas_snap,
                                   const double *kbt_snap,
                                   const double *b_field_snap,
                                   const double *divv_snap,
                                   const double *lturb_snap,
                                   const double *dv_snap,
                                   const double *cs_snap,
                                   const double *beta_snap,
                                   const double *rad_ic_zero,
                                   const double *rad_ic_m1_zero,
                                   const double *rad_ic_p1_zero,
                                   const double *n_gas_next_snap,
                                   const double *kbt_next_snap,
                                   const double *b_field_next_snap,
                                   const double *divv_next_snap,
                                   const double *lturb_next_snap,
                                   const double *dv_next_snap,
                                   const double *cs_next_snap,
                                   const double *beta_next_snap,
                                   const double *rad_ic_row_next,
                                   double rad_ic_m1_next_val,
                                   double rad_ic_p1_next_val,
                                   const double *qpi_batch,
                                   const double *qepri_batch,
                                   const double *fqe_flat,
                                   const int *np_min_qe,
                                   const double *tracer_mass,
                                   const unsigned char *disable_adiabatic,
                                   double *crp_state,
                                   double *cre_state,
                                   TracerFpGpuTimes *times,
                                   TracerFpCpuWs *ws);

int tracer_fp_batch_execute_parallel(int ntracer,
                                     const int *nsubsteps,
                                     const int *n_onsteps,
                                     const int *base_nsteps,
                                     const int *fp_cadence_steps,
                                     TracerFpIntegrationMode integration_mode,
                                     int allow_snapshot_interp,
                                     double elapsed_gyr,
                                     double dt_snap,
                                     double z_curr,
                                     double z_next,
                                     double requested_t_acc_direct_gyr,
                                     const CRspectrum *crp_grid,
                                     const CRspectrum *cre_grid,
                                     const double *n_gas_snap,
                                     const double *kbt_snap,
                                     const double *b_field_snap,
                                     const double *divv_snap,
                                     const double *lturb_snap,
                                     const double *dv_snap,
                                     const double *cs_snap,
                                     const double *beta_snap,
                                     const double *rad_ic_zero,
                                     const double *rad_ic_m1_zero,
                                     const double *rad_ic_p1_zero,
                                     const double *n_gas_next_snap,
                                     const double *kbt_next_snap,
                                     const double *b_field_next_snap,
                                     const double *divv_next_snap,
                                     const double *lturb_next_snap,
                                     const double *dv_next_snap,
                                     const double *cs_next_snap,
                                     const double *beta_next_snap,
                                     const double *rad_ic_row_next,
                                     double rad_ic_m1_next_val,
                                     double rad_ic_p1_next_val,
                                     const double *qpi_batch,
                                     const double *qepri_batch,
                                     const double *fqe_flat,
                                     const int *np_min_qe,
                                     const double *tracer_mass,
                                     const unsigned char *disable_adiabatic,
                                     double *crp_state,
                                     double *cre_state,
                                     TracerFpGpuTimes *times,
                                     int *bucket_calls_out,
                                     int *min_bucket_size_out,
                                     int *max_bucket_size_out);

#ifdef __cplusplus
}
#endif

#endif
